# https://taskfile.dev

version: '3'

vars:
  AWS_ACCOUNT:
    sh: echo $AWS_ACCOUNT_ID
  AWS_PROFILE:
    sh: echo $AWS_PROFILE
  AWS_REGION:
    sh: echo $AWS_REGION
  ACTIONS_FILE_PATH:
    sh: echo $PWD/actions.txt

includes:
  nuke:
    taskfile: ./cdk-base/nuke-account/Taskfile.yaml
    dir: ./cdk-base/nuke-account
  bootstrap:
    taskfile: ./cdk-base/bootstrap/Taskfile.yaml
    dir: ./cdk-base/bootstrap
  deploy:
    taskfile: ./cdk-base/deploy/Taskfile.yaml

tasks:

  build:
    desc: build the docker image for the server
    dir: infrastructure/lib/docker
    cmds:
      - docker build --build-arg GO_WORKDIR=server -t app:latest .
    silent: true

  docs:
    dir: ./docs
    cmds:
      - drawio -x -f png -o arc.png arc.drawio
    silent: true

  start-session:
    dir: ./scripts
    desc: starts a session to your running container
    cmds:
      - ./start-session.sh
    silent: true


